### ISSUE TITLE
TypeError: 'VideoFrameGenerator' object is not an iterator

### ISSUE THREAD

**Issue by JRunner97** [metal3d/keras-video-generators#15]
I'm getting an unexpected TypeError when running the code I got from https://medium.com/smileinnovation/training-neural-network-with-image-sequence-an-example-with-video-as-input-c3407f7a0b0f

I'm using the following on Windows 10
keras-video-generators==1.0.10
tensorflow==2.1.0
numpy==1.18.1
opencv-python==4.2.0.32
Keras==2.3.1
Python 3.7.5

`def train_model(model):
    # use sub directories names as classes
    classes = [i.split(os.path.sep)[1] for i in glob.glob('train\*')]
    classes.sort()
    
    # some global params
    SIZE = (224, 224)
    CHANNELS = 3
    NBFRAME = 64
    BS = 1
    EPOCHS=50

    # pattern to get videos and classes
    glob_pattern='train\{classname}\*.avi'

    # Create video frame generator
    train = VideoFrameGenerator(
        classes=classes, 
        glob_pattern=glob_pattern,
        nb_frames=NBFRAME,
        split=0.1, 
        shuffle=True,
        batch_size=BS,
        target_shape=SIZE,
        nb_channel=CHANNELS,
        use_frame_cache=False)
    
    valid = train.get_validation_generator()

    optimizer = keras.optimizers.Adam(0.001)

    model.compile(
        optimizer,
        'categorical_crossentropy',
        metrics=['acc']
    )

    model.fit(
        train,
        validation_data=valid,
        verbose=1,
        epochs=EPOCHS
    )`

`Traceback (most recent call last):
  File ".\net.py", line 491, in <module>
    train_model(model)
  File ".\net.py", line 485, in train_model
    epochs=EPOCHS
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 593, in _process_training_inputs    
    use_multiprocessing=use_multiprocessing)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 706, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py", line 747, in __init__
    peek, x = self._peek_and_restore(x)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py", line 850, in _peek_and_restore
    peek = next(x)
TypeError: 'VideoFrameGenerator' object is not an iterator`

**Comment by safusu** [comment]
I don't get that error when I use `from keras.layers import blah blah blah`, but I _do_ get it when I do `from tensorflow.keras.layers import blah blah blah` 

The version of keras bundled with tensorflow is (2.2.4-tf) vs 2.3.1 version of keras from `conda install -c conda-forge keras`

**Comment by metal3d** [comment]
Wow, weird...
It seems that "next(x)" won't work. I'm currently fixing the 1.0.11, so I will add a test for this one and try to fix.
Release will be done in a couple of hours

**Comment by JRunner97** [comment]
if I change the name of next(x) to __next(x)__ it seems to work

**Comment by metal3d** [comment]
That's the Iterator implementation that is needed. I've just added that to v1.0.11 branch.
That should be ok in next release, I only need to finish some points.

**Comment by metal3d** [comment]
The new version is now 1.0.11, can you please upgrade the package with `pip install --upgrade keras-video-generators` and tell me if it's OK now ?

Thanks a lot.

**Comment by safusu** [comment]
It's working for me, getting a

`Train for 365 steps, validate for 180 steps` 

message now

**Comment by metal3d** [comment]
Thanks a lot, it seems that it's now fixed.
Thanks for your reports !
